# Site wide configuration

title: Rafael Biriba Blog
locale: en_US
description: Technology and Development stuff!
logo: rb-logo.png
search: true
url: http://127.0.0.1:4000
baseurl: /blog

# Jekyll configuration

permalink:  /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: []
exclude: ["_original-theme-so-simple", "Gemfile", "Gemfile.lock", "config", "Capfile", "README.md"]


# Site owner
owner:
  name: Rafael Biriba
  avatar: https://www.gravatar.com/avatar/81d01f418d9288c14a94cd21b086156e?s=200
  email: radicalrj@gmail.com
  disqus-shortname: rafaelbiriba
  twitter: rafaelbiriba
  facebook: rafaelbiribarj
  github: rafaelbiriba
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: rafaelbiriba
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics: UA-7346716-1
    verify:
    ad-client: ca-pub-1303939561252359
    ad-slot: 4958401589
  bing-verify:
